
all:
	(cd 1-led* && make)
	(cd 2* && make)
	(cd 4* && make)
	(cd 11* && make)
	(cd comb* && make)

clean:
	(cd 1-led* && make clean)
	(cd 2* && make clean)
	(cd 4* && make clean)
	(cd 11* && make clean)
	(cd comb* && make clean)
